[build]
  command = "cd frontend && npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_URL = "https://repair-report.onrender.com/api"

[
redirects
]
  from = "/*"
  to = "/index.html"
  status = 200

[
headers
]
  for = "/*"
    [
headers.values
]
    Cache-Control = "no-store"